### PR TITLE
Initial version of puppetdb v4

### PR DESCRIPTION
**Pull request by russell**
Hi,

This commit is probably incomplete, i haven't had a chance to check all the existing v3 APIs that will be exposed by the v4 subclass.  But I thought it might be a good idea to get some feedback about what i have done so far.  Would this be something that you would be willing to merge upstream?

Cheers,
Russell

### CODE REVIEW

**Comment by hggh** [comment]
any news on pypuppetdb support v4?

**Comment by corey-hammerton** [comment]
Any updates?

**Comment by daenney** [comment]
This would need quite a bit of rework, and some other parts of PuppetDB too, in light of the 3.x release of PuppetDB. I don't think it's worth the effort supporting two "versions" of the v4 API. As such we're probably better off abandoning this and keeping 2.x support up to and including v3 and releasing a new major version of pypuppetdb that drops the legacy baggage and talks to PuppetDB 3.x over v4.

**Comment by corey-hammerton** [comment]
I will be able to work on this as a side project of mine. I will create a fork of this repository and work on it there while testing against a PuppetDB 3.x instance on a test environment.

**Pull request closed without merging**
