### PR TITLE
Remove docstring for ssl parameter which is unused

### PR DESCRIPTION
**Pull request by andrewspiers**
And document the ssl_verify parameter which is used.

### CODE REVIEW

**Comment by daenney** [comment]
Oh nice catch. Except for one thing, `ssl_verify` is not necessarily a bool. It can be `True`, `False` or a string representing the path on the filesystem to a certificate file for those cases where the CA you're using is not part of the OS truststore.

**Comment by andrewspiers** [comment]
Ah! I've changed it accordingly.

**Comment by daenney** [comment]
Could you squash the first two at least? It's a three line change in three commits :smile:.

**Comment by andrewspiers** [comment]
Sorry, I will send another PR.

**Pull request closed without merging**
