### PR TITLE
api/v3 Adding pagination functionality for supporting endpoints

### PR DESCRIPTION
**Pull request by corey-hammerton**
This is a squashed commit of https://github.com/puppet-community/pypuppetdb/pull/40

Exact same functionality updates

### CODE REVIEW

**Comment by daenney** [comment]
I've found another way to do this in the mean time by leveraging generators everywhere and always paging the queries. This makes the pagination automatic and completely transparent since you're still just iterating over the output. It also prevents a whole bunch of churn and adding all those options to every endpoint.

What do you think?

**Comment by corey-hammerton** [comment]
So long at it allows paging the results... How does that work exactly?

**Comment by Poil** [comment]
:+1:

**Comment by daenney** [comment]
Essentially what's happening is that under water we're batching the queries, at a rate of 200 resources per request but that's configurable. We then simply return a generator, so a `yield` which is smart enough to break once we've gone through all the resources, which can be read from `X-Records` header.

Essentially to the end user nothing changes, you're just iterating over the output, we're just being a lot smarter about fetching them.

**Comment by daenney** [comment]
In order to allow people to actually retrieve the length of the generator, which isn't possible to know until you've consumed the generator but we know because of `X-Records` we can return a generator-like object, essentially something that's iterable that also has `__len__` implemented on it.

**Comment by corey-hammerton** [comment]
I've opened https://github.com/puppet-community/pypuppetdb/pull/56 which is the same as this, but it passes all keyword arguments to the _query function instead of listing all the parameters individually.

**Pull request closed without merging**
